/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

/**
 *
 * @author erudzitis5
 */

import java.io.File;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class gui extends javax.swing.JFrame {

    /**
     * Creates new form gui
     */
    public gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rockbtn = new javax.swing.JButton();
        paperbtn = new javax.swing.JButton();
        scissorsbtn = new javax.swing.JButton();
        scorelabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        computerschoiceimg = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rockbtn.setIcon(new javax.swing.ImageIcon("S:\\Audzekni\\erudzitis5\\My Documents\\NetBeansProjects\\JavaApplication1\\src\\javaapplication1\\images\\rock-removebg-preview.png")); // NOI18N
        rockbtn.setActionCommand("rock");
        rockbtn.setMaximumSize(new java.awt.Dimension(71, 23));
        rockbtn.setMinimumSize(new java.awt.Dimension(71, 23));
        rockbtn.setPreferredSize(new java.awt.Dimension(71, 23));
        rockbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rockbtnActionPerformed(evt);
            }
        });

        paperbtn.setIcon(new javax.swing.ImageIcon("S:\\Audzekni\\erudzitis5\\My Documents\\NetBeansProjects\\JavaApplication1\\src\\javaapplication1\\images\\paper-removebg-preview.png")); // NOI18N
        paperbtn.setActionCommand("paper");
        paperbtn.setPreferredSize(new java.awt.Dimension(71, 23));
        paperbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paperbtnActionPerformed(evt);
            }
        });

        scissorsbtn.setIcon(new javax.swing.ImageIcon("S:\\Audzekni\\erudzitis5\\My Documents\\NetBeansProjects\\JavaApplication1\\src\\javaapplication1\\images\\scissors-removebg-preview.png")); // NOI18N
        scissorsbtn.setActionCommand("scissors");
        scissorsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scissorsbtnActionPerformed(evt);
            }
        });

        scorelabel.setText("Score: 0");
        scorelabel.setMaximumSize(new java.awt.Dimension(1, 14));
        scorelabel.setMinimumSize(new java.awt.Dimension(1, 14));

        jButton1.setText("Reset");
        jButton1.setPreferredSize(new java.awt.Dimension(20, 23));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Computers choice");

        computerschoiceimg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        computerschoiceimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/images/question-mark-removebg-preview.png"))); // NOI18N
        computerschoiceimg.setToolTipText("");
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scorelabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))
                    .addComponent(rockbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(paperbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(scissorsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(computerschoiceimg, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scorelabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scissorsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paperbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rockbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(computerschoiceimg, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Rock = 0
    // Paper = 1
    // Scissors = 2
    
    int score = 0;
    
    // https://coderanch.com/t/612146/java/update-image-JLabel-creating-window
    
    
    
    private void rockbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rockbtnActionPerformed
        int randomNum = ThreadLocalRandom.current().nextInt(0, 3);
        if(randomNum == 0){

            computerschoiceimg.setIcon(new javax.swing.ImageIcon("S:\\Audzekni\\erudzitis5\\My Documents\\NetBeansProjects\\JavaApplication1\\src\\javaapplication1\\images\\rock-removebg-preview.png"));
            
            JOptionPane.showMessageDialog(null, "It's a draw");
            score = score + 0;
            scorelabel.setText("Score: " + score);
        }
        else if(randomNum == 1){
            
            computerschoiceimg.setIcon(new javax.swing.ImageIcon("S:\\Audzekni\\erudzitis5\\My Documents\\NetBeansProjects\\JavaApplication1\\src\\javaapplication1\\images\\paper-removebg-preview.png"));
            
            JOptionPane.showMessageDialog(null, "You loose");
            score = score - 1;
            scorelabel.setText("Score: " + score);
        }
        else{
            
            computerschoiceimg.setIcon(new javax.swing.ImageIcon("S:\\Audzekni\\erudzitis5\\My Documents\\NetBeansProjects\\JavaApplication1\\src\\javaapplication1\\images\\scissors-removebg-preview.png"));
            
            JOptionPane.showMessageDialog(null, "You win");
            score = score + 1;
            scorelabel.setText("Score: " + score);
        }

        
                    // TODO add your handling code here:
    }//GEN-LAST:event_rockbtnActionPerformed

    private void paperbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paperbtnActionPerformed
        int randomNum = ThreadLocalRandom.current().nextInt(0, 3);
        if(randomNum == 0){
            
            computerschoiceimg.setIcon(new javax.swing.ImageIcon("S:\\Audzekni\\erudzitis5\\My Documents\\NetBeansProjects\\JavaApplication1\\src\\javaapplication1\\images\\rock-removebg-preview.png"));
            
            JOptionPane.showMessageDialog(null, "You win");
            score = score + 1;
            scorelabel.setText("Score: " + score);
        }
        else if(randomNum == 1){
            
            computerschoiceimg.setIcon(new javax.swing.ImageIcon("S:\\Audzekni\\erudzitis5\\My Documents\\NetBeansProjects\\JavaApplication1\\src\\javaapplication1\\images\\paper-removebg-preview.png"));
            
            JOptionPane.showMessageDialog(null, "It's a draw");
            score = score + 0;
            scorelabel.setText("Score: " + score);
        }
        else{
            
            computerschoiceimg.setIcon(new javax.swing.ImageIcon("S:\\Audzekni\\erudzitis5\\My Documents\\NetBeansProjects\\JavaApplication1\\src\\javaapplication1\\images\\scissors-removebg-preview.png"));
            
            JOptionPane.showMessageDialog(null, "You loose!");
            score = score - 1;
            scorelabel.setText("Score: " + score);
        }
    }//GEN-LAST:event_paperbtnActionPerformed

    private void scissorsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scissorsbtnActionPerformed
        int randomNum = ThreadLocalRandom.current().nextInt(0, 3);
        if(randomNum == 0){
            
            computerschoiceimg.setIcon(new javax.swing.ImageIcon("S:\\Audzekni\\erudzitis5\\My Documents\\NetBeansProjects\\JavaApplication1\\src\\javaapplication1\\images\\rock-removebg-preview.png"));
            
            JOptionPane.showMessageDialog(null, "You loose");
            score = score - 1;
            scorelabel.setText("Score: " + score);
        }
        else if(randomNum == 1){
            
            computerschoiceimg.setIcon(new javax.swing.ImageIcon("S:\\Audzekni\\erudzitis5\\My Documents\\NetBeansProjects\\JavaApplication1\\src\\javaapplication1\\images\\paper-removebg-preview.png"));
            
            JOptionPane.showMessageDialog(null, "You win");
            score = score + 1;
            scorelabel.setText("Score: " + score);
        }
        else{
            
            computerschoiceimg.setIcon(new javax.swing.ImageIcon("S:\\Audzekni\\erudzitis5\\My Documents\\NetBeansProjects\\JavaApplication1\\src\\javaapplication1\\images\\scissors-removebg-preview.png"));
            
            JOptionPane.showMessageDialog(null, "It's a draw");
            score = score + 0;
            scorelabel.setText("Score: " + score);
        }
    }//GEN-LAST:event_scissorsbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        score = 0;
        scorelabel.setText("Score: " + score);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel computerschoiceimg;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton paperbtn;
    private javax.swing.JButton rockbtn;
    private javax.swing.JButton scissorsbtn;
    private javax.swing.JLabel scorelabel;
    // End of variables declaration//GEN-END:variables
}
